---
- name: Automate SNOW - uptade change
  hosts: localhost
  connection: local
  vars:
    router_info: oioioioioi
  tasks:

  - name: Update incident
    servicenow.itsm.incident:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        validate_certs: false
      number: "{{ incident_number }}"
      other:
        work_notes: |
          {{ router_info.msg }}