---
- name: Automate SNOW - uptade change
  hosts: localhost
  connection: local
  vars:
    output_information: oioioioioi
  tasks:

  - name: Add a work note to the change request
    servicenow.itsm.change_request:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        validate_certs: false
      number: CHG0030902
      other:
        work_notes: |
         "{{ output_information }}"