---
- name: gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
    - name: gather router facts ios
      cisco.ios.facts:
        gather_subset: all
      when: ansible_network_os == 'ios'

    - name: gather router facts nxos
      cisco.nxos.nxos_facts:
        gather_subset: all
      when: ansible_network_os == 'nxos'

    - name: display version and serial number
      debug:
        msg: |
          The IOS/NXOS version is: {{ ansible_net_version }}
          The serial number is: {{ ansible_net_serialnum }}
      register: output_information

    - name: Set vars
      set_stats:
        data:
          sn_change_number: CHG0030902
          output_information: "{{ output_information }}"

