---
- name: Coletar informações sobre serviços no Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Obter informações sobre serviços
      ansible.windows.win_service_info:
      register: service_info

    - name: Exibir relatório de serviços
      debug:
        msg: "{{ service_info.services | map('combine', { 'nome_serviço': item.name, 'estado': item.state }) | list }}"
