---
- name: Automate SNOW - in_progress
  hosts: localhost
  connection: local
  vars:
    sn_incident_number: INC0012987
    output_information: "test"
  collections:
    - collections/ansible_collections/servicenow

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
#        number: "{{ sn_incident_number.msg }}"
        number: "{{ sn_incident_number }}"
        state: in_progress
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
          validate_certs: false
        caller: "{{ lookup('env', 'SN_USERNAME') }}"
        short_description: "teste de network - PROGRESSO!!!!!!!!!!!"
        description: "{{ output_information }}"
        impact: low
        urgency: low
      register: new_incident

    - debug:
        var: output_information
