---
- name: Automate SNOW - in_progress
  hosts: localhost
  connection: local
  vars:
    sn_incident_number: INC0012985
    output_information: "The IOS/NXOS version is: 17.03.06\nThe serial number is: 9XPDBWFSG7A\n"

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        state: in_progress
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        caller: "{{ lookup('env', 'SN_USERNAME') }}"
        short_description: "teste de network - PROGRESSO!!!!!!!!!!!"
        description: "{{ output_information }}"
        impact: low
        urgency: low
      register: new_incident

    - debug:
        var: output_information
