---
- name: Automate SNOW - in_progress
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    sn_incident_number:
    output_information:
  collections:
    - collections/ansible_collections/servicenow

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        number: "{{ sn_incident_number }}"
        state: in_progress
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
          validate_certs: false
        caller: "{{ lookup('env', 'SN_USERNAME') }}"
        short_description: "{{ output_information.msg }}"
        description: "{{ output_information }}"
        impact: low
        urgency: low
      register: in_progress_output
#      environment:
#        http_proxy: http://proxy.bos.example.com:8080
#        https_proxy: http://proxy.bos.example.com:8080

#    - debug:
#        var: output_information
#
#    - debug:
#        var: in_progress_output
