---
- name: Automate SNOW - Incident Create
  hosts: localhost
  connection: local
  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USERNAME }}"
          password: "{{ SNOW_PASSWORD }}"
        caller: "{{ lookup('env', 'SN_USERNAME') }}"
        short_description: "teste de network"
        description: "teste ansible!!!!!!!!!!!!!! NETWORK"
        impact: low
        urgency: low
      register: new_incident

    - set_fact:
        sn_incident_number: "{{ new_incident.record.number }}"

    - debug:
        var: new_incident.record.number

    - name: Set incident number
      set_stats:
        data:
          sn_incident_number: "{{ new_incident.record.number }}"

